import './../scss/main.scss';

// import './../styles/app.css';
//Importing all the images
import homeIcon1 from './images/dollar.png';
import homeIcon2 from './images/AngelaMerkel.jpg';
import homeIcon3 from './images/BorisBecker.png';
import homeIcon4 from './images/chinayuan.png';
import homeIcon5 from './images/DavidCassidy.jpg';
import homeIcon6 from './images/europe.png';
import homeIcon7 from './images/GregNorman.jpg';
import homeIcon8 from './images/health.jpg';
import homeIcon9 from './images/indonesia.png';
import homeIcon10 from './images/malaysia.png';
import homeIcon11 from './images/MarineLePen.jpg';
import homeIcon12 from './images/Mnangagwa.png';
import homeIcon13 from './images/QatarSaudi.jpg';
import homeIcon14 from './images/RatkoMladic.jpg';
import homeIcon15 from './images/RealMadrid.png';
import homeIcon16 from './images/RexTillerson.jpg';
import homeIcon17 from './images/singapore.png';
import homeIcon18 from './images/Tech.jpg';
import homeIcon19 from './images/Trump.png'; 
import homeIcon20 from './images/business.jpg';
import homeIcon21 from './images/search.png';
import homeIcon22 from './images/Currencies.png';

var homeImg1 = document.getElementById('dollar');
var homeImg2 = document.getElementById('AngelaMerkel');
var homeImg3 = document.getElementById('BorisBecker');
var homeImg4 = document.getElementById('chinayuan');
var homeImg5= document.getElementById('DavidCassidy');
var homeImg6 = document.getElementById('europe');
var homeImg7 = document.getElementById('GregNorman');
var homeImg8 = document.getElementById('health');
var homeImg9 = document.getElementById('indonesia');
var homeImg10 = document.getElementById('malaysia');
var homeImg11 = document.getElementById('MarineLePen');
var homeImg12 = document.getElementById('Mnangagwa');
var homeImg13 = document.getElementById('QatarSaudi');
var homeImg14 = document.getElementById('RatkoMladic');
var homeImg15 = document.getElementById('RealMadrid');
var homeImg16 = document.getElementById('RexTillerson');
var homeImg17 = document.getElementById('singapore');
var homeImg18 = document.getElementById('Tech');
var homeImg19 = document.getElementById('Trump');
var homeImg20 = document.getElementById('business'); 
var homeImg21 = document.getElementById('search');
var homeImg21 = document.getElementById('Currencies');
homeImg1.src = homeIcon1;
homeImg2.src = homeIcon2;
homeImg3.src = homeIcon3;
homeImg4.src = homeIcon4;
homeImg5.src = homeIcon5;
homeImg6.src = homeIcon6;
homeImg7.src = homeIcon7;
homeImg8.src = homeIcon8;
homeImg9.src = homeIcon9;
homeImg10.src = homeIcon10;
homeImg11.src = homeIcon11;
homeImg12.src = homeIcon12;
homeImg13.src = homeIcon13;
homeImg14.src = homeIcon14;
homeImg15.src = homeIcon15;
homeImg16.src = homeIcon16;
homeImg17.src = homeIcon17;
homeImg18.src = homeIcon18; 
homeImg19.src = homeIcon19; 
homeImg20.src = homeIcon20; 
homeImg21.src = homeIcon21;
homeImg22.src = homeIcon22;